/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogsRouteImport } from './routes/logs'
import { Route as PlanRouteImport } from './routes/plan'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TodayRouteImport } from './routes/today'
import { Route as ApiAppRouteImport } from './routes/api.app'
import { Route as ApiIntegrationsRouteImport } from './routes/api.integrations'
import { Route as ApiPushRouteImport } from './routes/api.push'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'
import { Route as ApiNotificationsRunRouteImport } from './routes/api.notifications.run'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsRoute = LogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanRoute = PlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAppRoute = ApiAppRouteImport.update({
  id: '/api/app',
  path: '/api/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIntegrationsRoute = ApiIntegrationsRouteImport.update({
  id: '/api/integrations',
  path: '/api/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushRoute = ApiPushRouteImport.update({
  id: '/api/push',
  path: '/api/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRunRoute = ApiNotificationsRunRouteImport.update({
  id: '/api/notifications/run',
  path: '/api/notifications/run',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/today': typeof TodayRoute
  '/api/app': typeof ApiAppRoute
  '/api/integrations': typeof ApiIntegrationsRoute
  '/api/push': typeof ApiPushRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notifications/run': typeof ApiNotificationsRunRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/today': typeof TodayRoute
  '/api/app': typeof ApiAppRoute
  '/api/integrations': typeof ApiIntegrationsRoute
  '/api/push': typeof ApiPushRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notifications/run': typeof ApiNotificationsRunRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/logs': typeof LogsRoute
  '/plan': typeof PlanRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/today': typeof TodayRoute
  '/api/app': typeof ApiAppRoute
  '/api/integrations': typeof ApiIntegrationsRoute
  '/api/push': typeof ApiPushRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notifications/run': typeof ApiNotificationsRunRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/insights'
    | '/login'
    | '/logs'
    | '/plan'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/today'
    | '/api/app'
    | '/api/integrations'
    | '/api/push'
    | '/api/auth/$'
    | '/api/notifications/run'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/insights'
    | '/login'
    | '/logs'
    | '/plan'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/today'
    | '/api/app'
    | '/api/integrations'
    | '/api/push'
    | '/api/auth/$'
    | '/api/notifications/run'
  id:
    | '__root__'
    | '/'
    | '/insights'
    | '/login'
    | '/logs'
    | '/plan'
    | '/privacy'
    | '/settings'
    | '/terms'
    | '/today'
    | '/api/app'
    | '/api/integrations'
    | '/api/push'
    | '/api/auth/$'
    | '/api/notifications/run'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  LogsRoute: typeof LogsRoute
  PlanRoute: typeof PlanRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  TodayRoute: typeof TodayRoute
  ApiAppRoute: typeof ApiAppRoute
  ApiIntegrationsRoute: typeof ApiIntegrationsRoute
  ApiPushRoute: typeof ApiPushRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiNotificationsRunRoute: typeof ApiNotificationsRunRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs': {
      id: '/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof LogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan': {
      id: '/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof PlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/app': {
      id: '/api/app'
      path: '/api/app'
      fullPath: '/api/app'
      preLoaderRoute: typeof ApiAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/integrations': {
      id: '/api/integrations'
      path: '/api/integrations'
      fullPath: '/api/integrations'
      preLoaderRoute: typeof ApiIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push': {
      id: '/api/push'
      path: '/api/push'
      fullPath: '/api/push'
      preLoaderRoute: typeof ApiPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/run': {
      id: '/api/notifications/run'
      path: '/api/notifications/run'
      fullPath: '/api/notifications/run'
      preLoaderRoute: typeof ApiNotificationsRunRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  LogsRoute: LogsRoute,
  PlanRoute: PlanRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  TodayRoute: TodayRoute,
  ApiAppRoute: ApiAppRoute,
  ApiIntegrationsRoute: ApiIntegrationsRoute,
  ApiPushRoute: ApiPushRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiNotificationsRunRoute: ApiNotificationsRunRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
